### ISSUE TITLE
What does it mean to "block" on events?

### ISSUE THREAD

**Issue by dgrotenstein** [150PLD-Fall2019/Reading#194]
Maybe someone with a bit more firmware knowledge can answer this... I am confused and google didn't help much. Thanks!

**Comment by ChrisEPhifer** [comment]
Sure, I can help!

A process is said to be _blocking_ if it is waiting for some event to occur or some I/O action to complete. It's a way of telling the scheduler in the operating system "this process can't do any useful work until this event occurs / the I/O finishes, so don't schedule it like normal until those events occur." In this use case, it prevents some latency by not scheduling processes that can't actually use the CPU cycles they're being given to execute due to a slow action they're trying to take, and giving those opportunities for using CPU time to processes that aren't currently waiting for some slow action to complete. 

This idea is also used to prevent multiple processes from accessing shared resources in ways that could cause problems, i.e. to solve the mutual exclusion problem. If process A and process B both need to access some file simultaneously, for instance (in order to communicate information to each other maybe), it would be disastrous to allow the processes to do things to that file on the whims of the process scheduler - you would have basically no guarantee that things are happening in the order you need them to for the modifications to be synchronized and the communication to make sense. A solution is to give the ability to say "hey, I'm accessing this resource; nobody else can touch it until I'm done." This _blocks_ the other processes from accessing the resource! The processes that want to use the shared resources that haven't 'won' the race to perform actions are put into a state that says "this resource isn't available to use yet, so just hang tight until it becomes available again and then you can mess with it." 

Hope that helps!

**Comment by dgrotenstein** [comment]
You're an icon, ty!
